services:
  proxy:
    container_name: luxuria-reverse-proxy

    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
        VITE_NODE_ENV: production
        VITE_carrersKey: ${VITE_carrersKey}
        VITE_contactUsKey: ${VITE_contactUsKey}

    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - luxuria-caddy-data:/data
      - luxuria-caddy-config:/config

    networks:
      - default

    restart: unless-stopped

volumes:
  luxuria-caddy-data:
  luxuria-caddy-config:

networks:
  default:
    name: luxuria-network
