services:
  proxy:
    container_name: luxuria-proxy

    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
        VITE_NODE_ENV: production

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - luxuria-caddy-data:/data
      - luxuria-caddy-config:/config

    restart: unless-stopped

volumes:
  luxuria-caddy-data:
  luxuria-caddy-config:
